sdsapp/urls.py
from django.urls import include, path
from .views import *
from django.urls import path


app_name = "sdsapp"

urlpatterns = [
    path('', home, name='home'),
    path('profile/', profile, name='profile'),
    
    path('projects/', project_list, name='projects'),
    path('grades/', grade_list, name='grades'),
    path('instructions/', instruction_list, name='instructions'),
    path('teacher_parents/', teacher_parent_list, name='teacher_parents'),
    path('subjects/', subject_list, name='subjects'),
    path('my_projects/', my_project_list, name='my_projects'),
    path('dashboards/', dashboard_list, name='dashboards'),
    


    
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', register_user, name="register"),
    path('logout/', logout_user, name='logout'),


    path('subject/form', subject_form, name='subject_form'),
    path('project/form', project_form, name='project_form'),

    # The <int:project_id> part of that URL pattern is used to capture any integer that is the route parameter, and stores that number in the project_id variable.
    path('projects/<int:project_id>/', project_details, name='project'),

    path('projects/<int:project_id>/form/', project_edit_form, name='project_edit_form'),


]

sdsproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls import path
from sdsapp.models import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sdsapp.urls')),

]

sdsapp/models.py
from django.db import models

# Create your models here.

sdsapp/models/dashboard.py
from django.db import models
from .teacher_parent import Teacher_Parent

class Dashboard(models.Model):

    name = models.CharField(max_length=55)
    teacher_parent = models.ForeignKey(Teacher_Parent, on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("dashboard")
        verbose_name_plural = ("dashboards")
    
    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse("dashboard_detail", kwargs={"pk": self.pk})
    

sdsapp/models/grade.py
from django.db import models

class Grade(models.Model):

    name = models.CharField(max_length=55)

    class Meta:
        verbose_name = ("grade")
        verbose_name_plural = ("grades")

    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse("grade_detail", kwargs={"pk": self.pk})
    

sdsapp/models/instruction.py
from django.db import models
# from .project import Project

class Instruction(models.Model):

    step_detail = models.CharField(max_length=55)
    # project =  models.ForeignKey(Project, on_delete=models.CASCADE)
    

    class Meta:
        verbose_name = ("instruction")
        verbose_name_plural = ("instructions")

    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse("instruction_detail", kwargs={"pk": self.pk})
    

sdsapp/models/modelfactory.py
import sqlite3

# Higher order function to create instances of models
# when performing single table queries
def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

sdsapp/models/project.py
from django.db import models
from .instruction import Instruction
from .grade import Grade
from .subject import Subject
from .instruction import Instruction 
from .grade import Grade
from .subject import Subject
from .teacher_parent import Teacher_Parent


class Project(models.Model):

    # If two models are related, you open the model that represents the table with the foreign key and add a ForeignKey field.
    name = models.CharField(max_length=55)
    instruction = models.CharField(max_length=500)
    grade = models.ForeignKey(Grade, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    teacher_parent = models.ForeignKey(Teacher_Parent, on_delete=models.CASCADE)
    image_path = models.CharField(max_length=255, null=True)
    supplies_needed = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

    class Meta:
        verbose_name = ("project")
        verbose_name_plural = ("projects")

    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse("project_detail", kwargs={"pk": self.pk})
    

sdsapp/models/saved_project.py
from django.db import models
from .project import Project
from .dashboard import Dashboard

class SavedProject(models.Model):

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    dashboard = models.ForeignKey(Dashboard, on_delete=models.CASCADE)
    note = models.CharField(max_length=255)

    class Meta:
        verbose_name = ("saved_project")
        verbose_name_plural = ("saved_projects")
    
    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse("saved_project_detail", kwargs={"pk": self.pk})
    

sdsapp/models/subject.py
from django.db import models

class Subject(models.Model):

    name = models.CharField(max_length=55)

    class Meta:
        verbose_name = ("subject")
        verbose_name_plural = ("subjects")

    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse("subject_detail", kwargs={"pk": self.pk})
    

sdsapp/models/teacher_parent.py
from django.db import models
from django.contrib.auth.models import User

class Teacher_Parent(models.Model):

    # Important: Never define your own User in a Django app. Seriously. Never. Always extend it. In this application, we are creating a seperate model and making a one-to-one relationship between it and the built-in User.

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    is_teacher = models.BooleanField(default=True)

    

sdsapp/views.py
from django.shortcuts import render

# Create your views here.

sdsapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

sdsapp/views/profile.py
from django.shortcuts import render

def profile(request):
    if request.method == 'GET':
        template = 'profile.html'
        context = {}

        return render(request, template, context)

sdsapp/templates/dashboards/list.html
{% extends 'shared/base.html' %}

{% block content %}
    <h1 style="margin-top : 20px;"><center>Dashboards</center></h1>
    <!-- Button trigger modal -->
    <center><button type="button" class="btn btn-primary btn-md dashboard" data-toggle="modal" data-target="#exampleModal">
    New Dashboard
    </button></center>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">New Dashboard</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{% url 'sdsapp:dashboards' %}" method="post">
                    <div class="modal-body">
                        {% csrf_token %}
                        <input id="dashboard" type="text" name="dashboard"  value="{{ dashboard.name }}" placeholder="Enter Dashboard Name" class="form-control" required>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" value="Add" class="btn btn-primary" name="actual_method" value="dashboard">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
    {% for dashboard in all_dashboards %}
    
        <h3 style="margin-left:15px;" classname"dashboard_name">{{ dashboard.name }}</h3>
            <div class="row row-cols-1 row-cols-md-3" style="margin-top: 20px; margin-left:auto; margin-right:auto">
            {% for saved_project in all_saved_projects %}

                {% if saved_project.dashboard_id == dashboard.id %}
                <div class="col mb-4">
                    <div class="card h-100 my_project_card">
                        <img src="{{saved_project.project.image_path}}" class="card-img-top" alt="{{saved_project.project.image_path}}">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'sdsapp:project' saved_project.project.id %}"> {{ saved_project.project.name }} </a></h5>
                            <p>Notes: {{ saved_project.note }}</p>
                            <p>Description: {{ saved_project.project.description }}</p>
                        </div>
                        <div class="card-footer text-muted">
                            <div>
                                <span class="badge badge-pill badge-info">{{saved_project.project.subject}}</span>
                                <span class="badge badge-pill badge-success">{{saved_project.project.grade}}</span>
                                <span class="badge badge-pill badge-warning">{{saved_project.project.teacher_parent.user.first_name}} {{saved_project.project.teacher_parent.user.last_name}}</span>
                            </div> 
                        </div>
                    </div>
                </div>
                {%endif%}
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

sdsapp/templates/grades/list.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Steam Driven School</title>
  </head>
  <body>
    <h1>Grades</h1>

    <ul>
    {% for grade in all_grades %}
        <li>
            {{ grade.name }}
        </li>
    {% endfor %}
    </ul>
  </body>
</html>

sdsapp/templates/home.html
{% extends 'shared/base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <center style="margin-top : 20px;">
            <img class="home-image" src="../../static/styles/SDS-train.png" alt="Steam driven train" width="300" height="300">
            <div style="margin-top : 20px;">
                <h1 class="homeTitle">Welcome to Steam Driven School</h1>
                <a href="{% url 'sdsapp:projects'%}" class="btn btn-primary active btn-lg " role="button" aria-pressed="true" style="border: 2px solid black;">Browse Projects</a>
                <a href=/project/form class="btn btn-primary active btn-lg " role="button" aria-pressed="true" style="border: 2px solid black;">Add New Project</a>
            </div>
        </center>
    {% else %}
        <center style="margin-top : 20px;">
        <img class="home-image" src="../../static/styles/SDS-train.png" alt="Steam driven train" width="300" height="300">
            <h1 class="homeTitle">Welcome to Steam Driven School</h1>
            <div style="margin-top : 20px;">
                <a href="{% url 'sdsapp:login'%}" class="btn btn-primary active btn-lg " role="button" aria-pressed="true" style="border: 2px solid black;">Login</a>
                <a href="{% url 'sdsapp:register'%}" class="btn btn-primary active btn-lg " role="button" aria-pressed="true" style="border: 2px solid black;">Register</a>
            </div>
        </center>
    {% endif %}

{% endblock %}

sdsapp/templates/instructions/list.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Steam Driven School</title>
  </head>
  <body>
    <h1>Instructions</h1>

    <ul>
    {% for instruction in all_instructions %}
        <li>
            {{ instruction.step_detail }}
        </li>
    {% endfor %}
    </ul>
  </body>
</html>

sdsapp/templates/my_projects/list.html
{% extends 'shared/base.html' %}

{% block content %}
    <h1 style="margin-top : 20px;"><center>My Projects</center></h1>
        <center><a href=/project/form class="btn btn-primary active btn-md" role="button" aria-pressed="true" style="border: 2px solid black;
    border-radius: 5px;">Add New Project</a></center>

    <div class="row row-cols-1 row-cols-md-3 " style="margin-top: 20px; margin-left:auto; margin-right:auto">
        {% for my_project in all_my_projects %}
        <div class="col mb-4">
            <div class="card h-100 my_project_card">
                <img src="{{my_project.image_path}}" class="card-img-top" alt="{{my_project.image_path}}">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'sdsapp:project' my_project.id %}"> {{ my_project.name }} </a>
                    </h5>
                    <p>{{ my_project.description }}</p>
                </div>
                <div class="card-footer text-muted">
                    <div>
                        <span class="badge badge-pill badge-info">{{my_project.subject}}</span>
                        <span class="badge badge-pill badge-success">{{my_project.grade}}</span>
                    </div> 
                </div> 
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

sdsapp/templates/projects/detail.html
{% extends 'shared/base.html' %}

{% block content %}
    <div class="card detail-card" style="margin-left: auto; margin-right: auto; margin-top: 50px; max-width: 1000px;">
        <div class="card-body">
            <center><h3 class="card-title">{{ project.name }}</h3></center>
            <div class="pills">
                <span class="badge badge-pill badge-info">{{project.subject}}</span>
                <span class="badge badge-pill badge-success">{{project.grade}}</span>
                <span class="badge badge-pill badge-warning">{{project.teacher_parent.user.first_name}} {{project.teacher_parent.user.last_name}}</span>
            </div>

            {% if current_user == project.teacher_parent_id %}
                <img src="{{project.image_path}}" class="details-image card-img-top" alt="{{project.image_path}}">
                <div class="row">
                    <h6 class="card-title col-sm-2">Description:</h6> 
                    <div class="col-sm-10">
                        <p class="card-text">{{ project.description }}</p>
                    </div>
                </div>
                <div class="row">
                    <h6 class="card-title col-sm-2">Supplies: </h6>
                    <div class="col-sm-10">
                        <p class="card-text">{{ project.supplies_needed }}</p>
                    </div>
                </div>
                <div class="row">
                    <h6 class="card-title col-sm-2">Instructions:</h6> 
                    <div class="col-sm-10">
                        <p class="card-text">{{ project.instruction }}</p>
                    </div>
                </div>
                <div class="row" style=" float: right;">
                    <div class="col-sm-1">
                        <form action="{% url 'sdsapp:project_edit_form' project.id %}" method="GET">
                            {% csrf_token %}
                            <button type="submit" class="btn" ><i class="fas fa-edit" style="color:gray;"></i></button>
                        </form>
                    </div>
                    <div class="col-sm-1">
                        <form action="{% url 'sdsapp:project' project.id %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="actual_method" value="DELETE">
                            <button type="submit" class="btn"><i class="fas fa-trash-alt" style="color:LightCoral;"></i></button>
                        </form>
                    </div>
                </div>
        

            {% else %}
                <img src="{{project.image_path}}" class="details-image card-img-top" alt="{{project.image_path}}">
                <div class="row">
                    <h6 class="card-title col-sm-2">Description: </h6>
                    <div class="col-sm-10">
                        <p class="card-text">{{ project.description }}</p>
                    </div>
                </div>
                <div class="row">
                    <h6 class="card-title col-sm-2">Supplies: </h6>
                    <div class="col-sm-10">
                        <p class="card-text">{{ project.supplies_needed }}</p>
                    </div>
                </div>
                <div class="row">
                    <h6 class="card-title col-sm-2">Instructions:</h6> 
                    <div class="col-sm-10">
                        <p class="card-text">{{ project.instruction }}</p>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

sdsapp/templates/projects/form.html
{% extends 'shared/base.html' %}

{% block content %}

    {% if project.id is not None %}
        <div class="card form-card" style="margin-left: auto; margin-right: auto; margin-top: 50px; max-width: 1000px;">
            <div class="card-body">
                <h3 class="card-title"><center>Edit Project</center></h1>
                <form action="{% url 'sdsapp:project' project.id %}" method="post">
    {% else %}
            <div class="card form-card" style="margin-left: auto; margin-right: auto; margin-top: 50px; max-width: 1000px;">
                <div class="card-body">
                <h3 class="card-title"><center>New Project</center></h3>
                <form action="{% url 'sdsapp:projects' %}" method="post">
                <div>
                    <div class="form-group row">
                        <label for="image" class="col-sm-2 col-form-label">Image: </label>
                        <div class="col-sm-10">
                            <button id="upload_widget" class="cloudinary-button">Upload files</button>
                        </div>
                    </div>

                    <script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript"></script>  

                    <script type="text/javascript">   
                    var myWidget = cloudinary.createUploadWidget({
                        cloudName: "bob1234girl", uploadPreset: "xcqyvhq9",
                        sources: [ 'local', 'url', 'image_search','camera','dropbox','facebook','instagram','shutterstock'],
                        googleApiKey: 'AIzaSyC1dya2DQfLq-DnA0D_HhRGuAasAPBT1eQ',
                        searchBySites: ["all", "cloudinary.com"],
                        searchByRights: true }, (error, result) => {
                            if (!error && result && result.event === "success") {
                                let new_image = result.info.url
                                document.getElementById("image_path").value=new_image
                            }
                        }); 

                    document.getElementById("upload_widget").addEventListener("click", function(){
                        myWidget.open();
                    }, false);
                    </script>
                    <input type="hidden" id="image_path" name="image_path">
                </div>
            
            {% endif %}

            {% csrf_token %}
            
            <div class="form-group row">
                <label for="project" class="col-sm-2 col-form-label">Project Name: </label>
                <div class="col-sm-10">
                    <input id="project" type="text" class="form-control" name="project" value="{{ project.name }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="subject" class="col-sm-2 col-form-label">Subject: </label>
                <div class="col-sm-10">
                    <select id="subject" type="text" class="form-control" name="subject" required>
                    {% for subject in all_subjects %}
                        <option {% if subject.id == project.subject_id %}selected{% endif %}  value="{{ subject.id }}">{{ subject.name }}</option>
                    {% endfor %}
                    </select>
                    <a href=/subject/form class="btn btn-light active btn-md " role="button" aria-pressed="true" style="margin-top : 15px;">Add New Subject</a>
                </div>
            </div>

            <div class="form-group row">
                <label for="grade" class="col-sm-2 col-form-label">Grade: </label>
                <div class="col-sm-10">
                    <select id="grade" type="text" class="form-control" name="grade" required>
                    {% for grade in all_grades %}
                        <option {% if grade.id == project.grade_id %}selected{% endif %} value="{{ grade.id }}">{{ grade.name }}</option>
                    {% endfor %}
                    </select>
                </div>
            </div>
            
            <div class="form-group row">
                <label for="decription" class="col-sm-2 col-form-label">Description: </label>
                <div class="col-sm-10">
                    <textarea id="description" class="form-control" name="description" rows="3" required>{{ project.description }}</textarea>
                </div>
            </div>

            <div class="form-group row">
                <label for="supplies" class="col-sm-2 col-form-label">Supplies: </label>
                <div class="col-sm-10">
                    <textarea id="supplies" class="form-control" name="supplies" rows="5" required>{{ project.supplies_needed }}</textarea>
                </div>
            </div>
            
            <div class="form-group row" >
                <label for="instruction" class="col-sm-2 col-form-label">Instructions: </label>
                <div class="col-sm-10">
                    <textarea id="instruction" class="form-control" name="instruction" rows="10" required>{{ project.instruction }}</textarea>
                </div>
            </div>

            {% if project.id is not None %}
                <input type="hidden" name="actual_method" value="PUT">
                <center><button type="submit" class="btn btn-primary btn-md">Update</button></center>
            {% else %}
                <center><button type="submit" class="btn btn-primary btn-md" name="actual_method" value="project">Create</button></center>
            {% endif %}        
            </form>
        </div>
    </div>
{% endblock %}

sdsapp/templates/projects/list.html
{% extends 'shared/base.html' %}

{% block content %}
    <h1 style="margin-top : 20px;"><center>Projects</center></h1>

    <div class="row row-cols-1 row-cols-md-3" style="margin-top: 20px; margin-left:auto; margin-right:auto">
      {% for project in all_projects %}
        <div class="col mb-4">
          <div class="card h-100 my_project_card">
            <img src="{{project.image_path}}" class="card-img-top" alt="{{project.image_path}}">
            <div class="card-body">
              <h5 class="card-title"><a href="{% url 'sdsapp:project' project.id %}"> {{ project.name }} </a></h5>
              <p>{{ project.description }}</p>
            </div>
            <div class="card-footer text-muted">
              <div>
                <span class="badge badge-pill badge-info">{{project.subject}}</span>
                <span class="badge badge-pill badge-success">{{project.grade}}</span>
                <span class="badge badge-pill badge-warning">{{project.teacher_parent.user.first_name}} {{project.teacher_parent.user.last_name}}</span>

                <!-- Button trigger modal -->
                <button type="button" class="btn btn-light btn-sm" data-toggle="modal" data-target="#exampleModal-{{project.id}}" style=" float: right;">
                  <i class="far fa-star"></i>
                </button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal-{{project.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="modalLabel">{{ project.name }}</h5>
                        <div>
                          <span class="badge badge-pill badge-info">{{project.subject}}</span>
                          <span class="badge badge-pill badge-success">{{project.grade}}</span>
                          <span class="badge badge-pill badge-warning">{{project.teacher_parent.user.first_name}} {{project.teacher_parent.user.last_name}}</span>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                      </div>
                      <form action="{% url 'sdsapp:projects' %}" method="post">
                        <div class="modal-body">
                          {% csrf_token %}
                          <input type="hidden" id="project" name="project" value={{project.id}}>
                            <input id="note" type="text" name="note"  value="{{ saved_project.note }}" placeholder="Enter Notes" class="form-control" required>
                          <select id="dashboard" type="text" class="form-control" name="dashboard" required>
                          {% for dashboard in all_dashboards %}
                            <option {% if dashboard.id == saved_project.subject_id %}selected{% endif %}  value="{{ dashboard.id }}">{{ dashboard.name }}</option>
                          {% endfor %}
                          </select>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <button type="submit" class="btn btn-primary" name="actual_method" value="saved_project">Save to Dashboard</button>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div> 
            </div> 
          </div>
        </div>
        
      {% endfor %}
    </div>
    
{% endblock %}

sdsapp/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Steam Driven School</title>

     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- base.css -->
    <link rel="stylesheet" href="{% static 'styles/base.css' %}" />
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/339bc0872b.js" crossorigin="anonymous"></script>

    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <a class="navbar-brand" href="{% url 'sdsapp:home' %}">
            <img src="../../static/styles/train-toy-svgrepo-com.svg" width="30" height="30" class="d-inline-block align-top" alt="">
            Steam Driven School
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sdsapp:home' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sdsapp:projects' %}">Projects</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sdsapp:my_projects' %}">My Projects</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sdsapp:dashboards' %}">Dashboards</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sdsapp:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sdsapp:profile' %}">{{user.first_name}} <i class="fas fa-user-circle"></i></a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sdsapp:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sdsapp:register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    
    
    {% block content %}
    {% endblock %}
    <script src="static/scripts/sds.js"></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

sdsapp/templates/subjects/form.html
{% extends 'shared/base.html' %}

{% block content %}
  <div class="card form-card" style="width: 20rem; margin-left: auto; margin-right: auto; margin-top: 50px;">
    <div class="card-body" style="margin-left: auto; margin-right: auto; ">
      <h3 class="card-title"><center>New Subject</center></h1>
      <form action="{% url 'sdsapp:subjects' %}" method="post">
        {% csrf_token %}
            <input id="subject" type="text" name="subject"  value="{{ project.subject }}" placeholder="Enter Subject Name" class="form-control" required>
        <center>
          <button type="submit" class="btn btn-primary btn-md" style="margin-top: 10px;">Submit</button>
        </center>
      </form>
    </div>
  </div>
{% endblock %}

sdsapp/templates/subjects/list.html
{% extends 'shared/base.html' %}

{% block content %}
    <div class="card subject-card" style="width: 20rem; margin-left: auto; margin-right: auto; margin-top: 50px;">  
        <div class="card-body">
            <center><h3 class="card-title">Subjects</h3>
            <ol>
                {% for subject in all_subjects %}
                    <li style="text-align:left">
                        {{ subject.name }}
                    </li>
                {% endfor %}
            </ol>
        </div>
    </div>
{% endblock %}